
package com.infoyb.supplier.base;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-12-06T10:10:54.282+08:00
 * Generated source version: 2.4.3
 * 
 */
public final class OutUnitService_OutUnitServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:SubmitOutUnitService", "SubmitOutUnitService");

    private OutUnitService_OutUnitServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SubmitOutUnitService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SubmitOutUnitService ss = new SubmitOutUnitService(wsdlURL, SERVICE_NAME);
        OutUnitService port = ss.getOutUnitServiceImplPort();

        {
        System.out.println("Invoking outUnitSubmit...");
        com.infoyb.supplier.base.OutUnitSubmit _outUnitSubmit_parameters = null;
        com.infoyb.supplier.base.OutUnitSubmitResponse _outUnitSubmit__return = port.outUnitSubmit(_outUnitSubmit_parameters);
        System.out.println("outUnitSubmit.result=" + _outUnitSubmit__return);


        }

        System.exit(0);
    }

}
