package com.infoyb.supplier.base;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-12-06T10:10:54.427+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "urn:SubmitOutUnitService", name = "OutUnitService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OutUnitService {

    @WebMethod(action = "urn:SubmitOutUnitService")
    @WebResult(name = "outUnitSubmitResponse", targetNamespace = "urn:SubmitOutUnitService", partName = "parameters")
    public OutUnitSubmitResponse outUnitSubmit(
        @WebParam(partName = "parameters", name = "outUnitSubmit", targetNamespace = "urn:SubmitOutUnitService")
        OutUnitSubmit parameters
    );
}
